baseurl = "/"
languageCode = "en-us"
title = "codelyon"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
disqusShortname = "marcuslyons-com"
# Enable gogle analytics by entering your tracking code
googleAnalytics = "UA-113593889-1"
theme = "hugo-minimalist-theme"

[params]
    site_author = "Marcus Lyons"
    site_description = "Random thoughts and musings on software development, life, and hobbies by Marcus Lyons."
    location = "Boise, Idaho"
    # Link custom assets relative to /static
    avatar = "img/marcus1.jpg"
    header_background = "img/minimal-tech-table.jpg"
    header_title = "codeLyon"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "codelyon"
    facebook  = ""
    linkedin  = "marcuslyons"
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "malyons"
    gplus     = ""
